SELECT F."NAME", COUNT(*) as "PRF_CNT"
FROM "COURSE" AS A, "FACULTY" AS F
WHERE A."PROF_ID" = F."ID" AND
	A."COURSE_ID" IN (SELECT C."COURSE_ID"
		FROM "COURSE" AS C, "COURSE_REGISTRATION" AS R
		WHERE C."COURSE_ID" = R."COURSE_ID" AND (C."YEAR" BETWEEN 2013 AND 2018)
		GROUP BY C."COURSE_ID"
		HAVING (COUNT(*)*100/C."MAX_ENROLLEES") > 80
		ORDER BY C."COURSE_ID" ASC)
GROUP BY F."NAME"
ORDER BY COUNT(*) DESC;